# Generated by Django 3.2.6 on 2021-08-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('python', 'python'), ('java', 'java')], default='python', max_length=100)),
                ('style', models.CharField(choices=[('friendly', 'friendly'), ('solid', 'solid')], default='friendly', max_length=30)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
